### ISSUE TITLE
Change the example text on the new course form

### ISSUE THREAD

**Issue by Sumukh** [okpy/ok#1122]
A few people have created courses with the offering `cal/cs61a/sp16` and a name of `CS 61A`  since that's what the example text uses

I've been manually changing these - and no one else can make a cal/cs61a/sp16 course now.

**Comment by MrVantastic** [comment]
I'd like to work on this, if that's okay! Is it just a matter of changing the example text to something more generic on the forms.py file, or is there more to it?

**Comment by Sumukh** [comment]
That's it.
