### ISSUE TITLE
More User-Friendly Date Input

### ISSUE THREAD

**Issue by epai** [okpy/ok#1208]
Currently, dates are specified using a standard formatted string. e.g. "2017-12-21 23:59:59"

That's not readable or user friendly to input.  We should instead use something like a date picker:

Something like:  

[![this](https://www.jqueryscript.net/images/Clean-jQuery-Date-Time-Picker-Plugin-datetimepicker.jpg)](https://www.jqueryscript.net/time-clock/Clean-jQuery-Date-Time-Picker-Plugin-datetimepicker.html)

**Comment by itsnshaw** [comment]
Fixed by #1309
