### ISSUE TITLE
Deploy ok to a self-hosted VPS

### ISSUE THREAD

**Issue by billzhonggz** [okpy/ok#1337]
I am trying to deploy ok to a VPS for auto-grading purposes for my college. 

* By default, ok is running in a development environment, so that I modified `manage.py` and `wsgi.py` to the production environment.
* After I done above, when I run the script `manage.py` or `gunicorn`, it will ask me to set Google or Microsoft OAuth ID and key. But the instruction [here](https://github.com/okpy/ok/wiki/Deploying-OK-as-a-self-hosted-service) is not working.
* I cannot find any deployment instructions for auto-grading stuff.

**Help wanted:**
* Can any provide a newer deployment instruction for self-hosted purposes?
* Can ok server authenticate users **without** Google or Microsoft API?

**Comment by Sumukh** [comment]
> I cannot find any deployment instructions for auto-grading stuff.

This is a separate repository. You may you use our hosted autograding service if you'd like. We do also grant access to the repository if you _must_ self host but it's a lot of hassle - feel free to email the folks listed at okpy.org for access. 

> Google or Microsoft OAuth ID and key

This is required. There is no other way for users to login right now. 

If `GOOGLE_ID` and `GOOGLE_SECRET` is set, you should be good to go - what error do you get?

**Comment by billzhonggz** [comment]
Thanks for reply. The reason I don't want to use Google stuff is we are deploying the ok server in mainland China where Google is blocked.
