### ISSUE TITLE
"OK" Logo in Admin Mode should navigate to the main index page

### ISSUE THREAD

**Issue by pbitutsky** [okpy/ok#1344]
Currently, clicking the "OK" logo in the top left corner of the admin mode (or staff mode, not sure about terminology), will navigate the user to the _assignments page of the first course for which the user is an admin (staff)._ This feels very strange to me. Clicking the "OK" logo should navigate to either  the list of all courses (https://okpy.org/admin/course/) or the okpy student mode index page (https://okpy.org/). 

<img width="714" alt="screen shot 2019-01-15 at 12 01 06 am" src="https://user-images.githubusercontent.com/6360587/51159772-df0ef980-1858-11e9-9530-04c84d0ac1f2.png">

**Comment by Royserg** [comment]
Hi @pbitutsky 
I would like to try fixing this one.

**Comment by harsh1599** [comment]
Hi! Has this issue already been resolved or I can work on it?

**Comment by colinschoen** [comment]
@harsh1599 Thanks for the interest! It looks like it is being worked on here #1345. There are other issues tagged as good for first timers too!

**Comment by iamharshgupta** [comment]
I would like to start working on this issue . Should I go ahead ?

**Comment by colinschoen** [comment]
You can see the status of the pull request here

https://github.com/okpy/ok/pull/1345

It looks like this is ready to be shipped so picking another issue is the way to go.
