### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by colinschoen** [okpy/ok#1354]
The build looks broken. https://circleci.com/gh/okpy/ok

**Comment by ja5087** [comment]
I tried rebuilding a past known working commit and it still failed. Do you have any idea why this might be the case?

**Comment by ja5087** [comment]
Problem found: our requirements call for Werkzeug>=0.7. The tests pass under 0.14.1, but not >=0.15.0 onwards. Will quickly patch requirements.txt until we figure out how to fix the tests.

**Comment by colinschoen** [comment]
Thank you!
