### ISSUE TITLE
Edit Participant window Role defaults to Student

### ISSUE THREAD

**Issue by syoh** [okpy/ok#1358]
As an instructor, when I use Edit Participant window, my Role defaults to Student.

Unless I change the dropdown to Instructor each time, I will unintentionally change my Role to Student
![Sang Yun Oh   PSTAT134 234  Spring 2019 ](https://user-images.githubusercontent.com/1441512/56075634-757c8980-5d7a-11e9-9458-c4c6dea01899.png)

**Comment by pbitutsky** [comment]
I will work on fixing this.
