### ISSUE TITLE
Ambiguous timezone abbreviations

### ISSUE THREAD

**Issue by axmmisaka** [okpy/ok#1393]
In cs61c appointment system, some people are getting confused if CST means China Standard Time or Central Standard time. It'd be helpful if it can show it's UTC+-? or some additional tz information; it would also be better to add a toggle to switch from local timezone to a unified one (PDT, for example).

I guess relevant utils are here
https://github.com/okpy/ok/blob/253243bed7cdfa52e3c26aee39ce065d85a393fa/server/utils.py#L59-L113

https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations

**Comment by chrononyan** [comment]
The example in OP targets OH Queue (Cal-CS-61A-Staff/oh-queue#212), though this could still apply here if Ok uses `%Z` anywhere (don't think it does).

**Comment by axmmisaka** [comment]
https://github.com/Cal-CS-61A-Staff/oh-queue/pull/212 is merged, I'll close this issue...
